
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 21 18:57:22 CEST 2015
//----------------------------------------------------

package model;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int LEFTBRACKET = 8;
  public static final int DIVIDE = 39;
  public static final int RIGHT_BRACKET2 = 17;
  public static final int FUNCTION = 10;
  public static final int CHAR = 55;
  public static final int EQUALS = 30;
  public static final int CASE = 28;
  public static final int RIGHTBRACKET = 9;
  public static final int GREATER = 31;
  public static final int REPEAT = 19;
  public static final int INT = 51;
  public static final int ARRAY = 15;
  public static final int MINUS = 37;
  public static final int LESS = 32;
  public static final int FOR = 22;
  public static final int WRITE = 42;
  public static final int AND = 49;
  public static final int NOT = 41;
  public static final int SEMICOLON = 4;
  public static final int NIL = 47;
  public static final int OR = 48;
  public static final int LEFT_BRACKET2 = 16;
  public static final int COMMA = 14;
  public static final int BEGIN = 12;
  public static final int UNTIL = 21;
  public static final int MULTIPLY = 38;
  public static final int GREATER_OR_EQUALS = 34;
  public static final int WRITELN = 43;
  public static final int IF = 25;
  public static final int DOT = 6;
  public static final int OF = 29;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int ADD = 36;
  public static final int MOD = 40;
  public static final int IDE = 52;
  public static final int ASSINGMENT = 50;
  public static final int READLN = 45;
  public static final int REAL = 53;
  public static final int COLON = 11;
  public static final int ELSE = 27;
  public static final int READ = 44;
  public static final int TO = 23;
  public static final int WHILE = 18;
  public static final int READKEY = 46;
  public static final int NOT_EQUALS = 35;
  public static final int THEN = 26;
  public static final int END = 13;
  public static final int STRING = 54;
  public static final int DOWNTO = 24;
  public static final int USES = 3;
  public static final int LESS_OR_EQUALS = 33;
  public static final int VAR = 5;
  public static final int PROCEDURE = 7;
  public static final int DO = 20;
}

