
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 19 17:43:39 CEST 2015
//----------------------------------------------------

package model;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int LEFTBRACKET = 8;
  public static final int DIVIDE = 40;
  public static final int RIGHT_BRACKET2 = 17;
  public static final int FUNCTION = 10;
  public static final int CHAR = 56;
  public static final int ASSIGNMENT = 23;
  public static final int EQUALS = 31;
  public static final int COMMENT = 58;
  public static final int CASE = 29;
  public static final int RIGHTBRACKET = 9;
  public static final int GREATER = 32;
  public static final int REPEAT = 19;
  public static final int INT = 52;
  public static final int ARRAY = 15;
  public static final int MINUS = 38;
  public static final int LESS = 33;
  public static final int FOR = 22;
  public static final int WRITE = 43;
  public static final int AND = 50;
  public static final int NOT = 42;
  public static final int SEMICOLON = 4;
  public static final int NIL = 48;
  public static final int OR = 49;
  public static final int LEFT_BRACKET2 = 16;
  public static final int COMMA = 14;
  public static final int BEGIN = 12;
  public static final int UNTIL = 21;
  public static final int MULTIPLY = 39;
  public static final int GREATER_OR_EQUALS = 35;
  public static final int WRITELN = 44;
  public static final int IF = 26;
  public static final int DOT = 6;
  public static final int OF = 30;
  public static final int BOOLEAN = 57;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int ADD = 37;
  public static final int MOD = 41;
  public static final int IDE = 53;
  public static final int ASSINGMENT = 51;
  public static final int READLN = 46;
  public static final int REAL = 54;
  public static final int COLON = 11;
  public static final int ELSE = 28;
  public static final int READ = 45;
  public static final int TO = 24;
  public static final int WHILE = 18;
  public static final int READKEY = 47;
  public static final int NOT_EQUALS = 36;
  public static final int THEN = 27;
  public static final int END = 13;
  public static final int STRING = 55;
  public static final int DOWNTO = 25;
  public static final int USES = 3;
  public static final int LESS_OR_EQUALS = 34;
  public static final int VAR = 5;
  public static final int PROCEDURE = 7;
  public static final int DO = 20;
}

